mingmar4thsem/Controllers/EmployeeSalaryDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mingmar4thsem.Models;

namespace mingmar4thsem.Controllers
{
    public class EmployeeSalaryDetailController : Controller
    {
        // GET: EmployeeSalaryDetail

        public void SelectDropDown()
        {
            var empList = db.tbl_employee.ToList();
            ViewBag.empList = new SelectList(empList, "id", "name");
        }

        Entities db = new Entities();
        public ActionResult ShowEmpSalDetails()
        {
            List<employee_salary_details> all_data = db.employee_salary_details.ToList();
            SelectDropDown();
            return View(all_data);
        }

        

        public ActionResult Edit(int id)
        {
            employee_salary_details empDetail = db.employee_salary_details.Find(id);
            var empList = db.tbl_employee.ToList();
            ViewBag.empList = new SelectList(empList, "id", "name");
            return View(empDetail);
        }

        public ActionResult SaveEdit(employee_salary_details empDetails)
        {
            db.Entry(empDetails).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("ShowEmpSalDetails");
        }

        public ActionResult Delete(int id)
        {
            employee_salary_details empDetails = db.employee_salary_details.Find(id);
            db.employee_salary_details.Remove(empDetails);
            db.SaveChanges();
            return RedirectToAction("ShowEmpSalDetails");

        }

        [HttpPost]
        public ActionResult Create(employee_salary_details empSalDetails)
        {
            db.employee_salary_details.Add(empSalDetails);
            db.SaveChanges();
            return RedirectToAction("ShowEmpSalDetails");

        }

        public ActionResult Search(DateTime? beginDate,DateTime? endDate,int? searchedID)
        {
            List<employee_salary_details> searchedData = new List<employee_salary_details>();
            if(searchedID != null)
            {
                searchedData = db.employee_salary_details.Where(x => x.employee_id == searchedID).ToList();
                if (beginDate != null && endDate != null)
                {
                    searchedData = searchedData.Where(x => beginDate <= x.paid_date && endDate >= x.paid_date).ToList();
                }
            }
            if (beginDate != null && endDate != null)
            {
                searchedData = db.employee_salary_details.Where(x => beginDate <= x.paid_date && endDate >= x.paid_date).ToList();
            }


            SelectDropDown();
            return View("ShowEmpSalDetails",searchedData);
        }

    }
}

mingmar4thsem/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mingmar4thsem.Models;

namespace mingmar4thsem.Controllers
{
    public class PersonController : Controller
    {
        Entities db = new Entities();
        // GET: Person
        public ActionResult inputPerson()
        {
            List<person> all_data = db.people.ToList();
            return View(all_data);
        }
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult SaveData(person person)
        {
            db.people.Add(person);
            db.SaveChanges();
            return RedirectToAction("inputPerson");
        }

        public ActionResult Edit(int id)
        {
            person person1 = db.people.Find(id);
            return View(person1);
        }

        public ActionResult DeletePerson(int id)
        {
            person searched = db.people.Find(id);
            db.people.Remove(searched);
            db.SaveChanges();
            return RedirectToAction("inputPerson");
        }

        public ActionResult UpdateData(person person)
        {
            db.Entry(person).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("inputPerson");
        }



    }
}

mingmar4thsem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("INPUT", "inputPerson","Person")</li>
                    <li>@Html.ActionLink("Student", "Index", "Student")</li>
                    <li>@Html.ActionLink("Teacher","TableView","Teacher")</li>
                    <li>@Html.ActionLink("Employee","ShowEmployees","Employee")</li>
                    <li>@Html.ActionLink("Salary Details","ShowEmpSalDetails","EmployeeSalaryDetail")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>